package compose.miniapp.compiler

import java.io.File

// ---------- 工程装配器 + 校验器（规格 §9） ----------

data class PageArtifact(
    val tree: UiTree,
    val wxml: String,
    val wxss: String,
    val js: String,
    val json: String,
)

object Assembler {

    private val appJsonTemplate = """
        {
          "pages": %PAGES%,
          "window": {
            "navigationBarBackgroundColor": "#ffffff",
            "navigationBarTextStyle": "black",
            "navigationBarTitleText": "MiniApp",
            "backgroundColor": "#f7f8fa"
          },
          "sitemapLocation": "sitemap.json",
          "lazyCodeLoading": "requiredComponents"
        }
    """.trimIndent()

    private val projectConfigTemplate = """
        {
          "description": "auto-generated by compose-miniapp transpiler",
          "appid": "touristappid",
          "projectname": "compose-miniapp",
          "miniprogramRoot": "./",
          "compileType": "miniprogram",
          "setting": { "es6": true, "minified": true }
        }
    """.trimIndent()

    private val sitemapTemplate = """
        {
          "desc": "auto-generated",
          "rules": [{ "action": "allow", "page": "*" }]
        }
    """.trimIndent()

    fun assemble(artifacts: List<PageArtifact>, outDir: File, extraDir: File? = null) {
        outDir.deleteRecursively()
        outDir.mkdirs()

        for (a in artifacts) {
            val pageDir = File(outDir, "pages/" + a.tree.pageName)
            pageDir.mkdirs()
            File(pageDir, a.tree.pageName + ".wxml").writeText(a.wxml)
            File(pageDir, a.tree.pageName + ".wxss").writeText(a.wxss)
            File(pageDir, a.tree.pageName + ".js").writeText(a.js)
            File(pageDir, a.tree.pageName + ".json").writeText(a.json)
        }

        val pagePaths = artifacts.map { it.tree.pagePath }

        // miniAppMain 目录（可选）：logic.js 真实实现 + miniapp.config.json（tabBar/窗口）
        var configText: String? = null
        if (extraDir != null && extraDir.isDirectory) {
            val cfg = File(extraDir, "miniapp.config.json")
            if (cfg.exists()) configText = cfg.readText()
        }
        val tabBar = configText?.let { extractJsonBlock(it, "tabBar") }
        val windowConfig = configText?.let { extractJsonBlock(it, "window") }

        val entryPage = configText?.let { extractJsonStringField(it, "entryPage") }
        val orderedPages = if (entryPage != null && entryPage in pagePaths) {
            listOf(entryPage) + pagePaths.filter { it != entryPage }.sorted()
        } else {
            pagePaths.sorted()
        }
        val pages = orderedPages.map { "\"$it\"" }
        var appJson = appJsonTemplate.replace("%PAGES%", "[" + pages.joinToString(", ") + "]")
        if (tabBar != null) appJson = appJson.replace("\"window\":", "\"tabBar\": $tabBar,\n  \"window\":")
        if (windowConfig != null) {
            val current = extractJsonBlock(appJson, "window") ?: "{}"
            appJson = appJson.replace(current, windowConfig)
        }
        File(outDir, "app.json").writeText(appJson)
        val userAppJs = if (extraDir != null) File(extraDir, "app.js") else null
        val userAppWxss = if (extraDir != null) File(extraDir, "app.wxss") else null
        File(outDir, "app.js").writeText(
            if (userAppJs != null && userAppJs.exists()) userAppJs.readText() else "App({});\n"
        )
        File(outDir, "app.wxss").writeText(
            if (userAppWxss != null && userAppWxss.exists()) userAppWxss.readText()
            else "page { background-color: #f7f8fa; }\n"
        )
        File(outDir, "project.config.json").writeText(projectConfigTemplate)
        File(outDir, "sitemap.json").writeText(sitemapTemplate)

        val logicDir = File(outDir, "logic")
        logicDir.mkdirs()
        val userLogic = if (extraDir != null) File(extraDir, "logic.js") else null
        if (userLogic != null && userLogic.exists()) {
            userLogic.copyTo(File(logicDir, "logic.js"), overwrite = true)
        } else {
            File(logicDir, "logic.js").writeText("// auto-generated logic layer placeholder\nmodule.exports = {};\n")
        }

        val userAssets = if (extraDir != null) File(extraDir, "assets") else null
        if (userAssets != null && userAssets.isDirectory) {
            userAssets.copyRecursively(File(outDir, "assets"), overwrite = true)
        }

        verify(artifacts, outDir)
    }

    // 提取 JSON 中某 key 的平衡花括号块（如 "tabBar": { ... }）
    private fun extractJsonBlock(src: String, key: String): String? {
        val m = Regex("\"$key\"\\s*:\\s*[{]").find(src) ?: return null
        var depth = 1  // 起始 '{' 计入深度，避免嵌套对象提前截断
        var i = m.range.last + 1
        while (i < src.length) {
            when (src[i]) {
                '{' -> depth++
                '}' -> { depth--; if (depth == 0) return src.substring(m.range.last, i + 1) }
            }
            i++
        }
        return null
    }

    // 提取嵌套 JSON 字段值："window": { ... "navigationBarTitleText": "xxx" ... }
    private fun extractJsonField(src: String, outer: String, field: String): String? {
        val block = extractJsonBlock(src, outer) ?: return null
        val m = Regex("\"$field\"\\s*:\\s*\"([^\"]*)\"").find(block) ?: return null
        return m.groupValues[1]
    }

    private fun extractJsonStringField(src: String, field: String): String? {
        val m = Regex("\"$field\"\\s*:\\s*\"([^\"]*)\"").find(src) ?: return null
        return m.groupValues[1]
    }

    private fun verify(artifacts: List<PageArtifact>, outDir: File) {
        val errors = mutableListOf<String>()
        for (a in artifacts) {
            val pageDir = File(outDir, "pages/" + a.tree.pageName)
            val handlerIds = a.tree.eventHandlers.map { it.handlerId }.toSet()
            val wxmlBindings = Regex("(bindtap|bindinput)=\"([^\"]+)\"").findAll(a.wxml)
                .map { it.groupValues[2] }.toList()
            for (h in wxmlBindings) {
                if (h !in handlerIds) errors.add("${a.tree.pagePath}: WXML 引用未生成的 handler '$h'")
            }
            val dataKeys = a.tree.stateFields.map { it.name }.toSet()
            val refs = Regex("\\{\\{([a-zA-Z_][a-zA-Z0-9_]*)\\}\\}").findAll(a.wxml)
                .map { it.groupValues[1] }.toList()
            for (r in refs) {
                // 'index' 是 wx:for 内建变量，不在页面 data 中
                if (r != "index" && r !in dataKeys) errors.add("${a.tree.pagePath}: WXML 引用未注册 data key '$r'")
            }
            for (m in Regex("wx:for=\"\\{\\{([^}]+)}}").findAll(a.wxml)) {
                val field = m.groupValues[1]
                val st = a.tree.stateFields.firstOrNull { it.name == field }
                if (st == null || st.kind != "LIST") errors.add("${a.tree.pagePath}: wx:for 数据源 '$field' 不是 LIST 状态")
            }
            for (ext in listOf("wxml", "wxss", "js", "json")) {
                if (!File(pageDir, a.tree.pageName + "." + ext).exists()) {
                    errors.add("${a.tree.pagePath}: 缺少产物文件 .$ext")
                }
            }
        }
        if (errors.isNotEmpty()) {
            throw CompileException("E1010", "产物校验失败：\n  " + errors.joinToString("\n  "), 0, 0)
        }
    }
}
