package compose.miniapp.compiler

// ---------- WXML / WXSS 生成器（规格 §5.3） ----------
// 纯字符串拼接，确定性输出；WXML 属性顺序固定：class → 数据 → 事件。

object WxmlGenerator {

    fun generate(tree: UiTree): String {
        val sb = StringBuilder()
        emitNode(sb, tree.root, 0)
        return sb.toString()
    }

    private fun emitNode(sb: StringBuilder, node: UiNode, depth: Int) {
        val ind = "  ".repeat(depth)
        when (node.type) {
            ComponentType.List -> {
                val ctx = node.loop ?: error("List 缺少 loop 上下文")
                val cls = node.style?.className
                sb.append(ind).append("<block wx:for=\"{{${ctx.itemsField}}}\"")
                if (ctx.keyField != null) sb.append(" wx:key=\"${ctx.keyField}\"")
                if (cls != null) sb.append(" class=\"$cls\"")
                sb.append(">\n")
                node.children.forEach { emitNode(sb, it, depth + 1) }
                sb.append(ind).append("</block>\n")
            }
            ComponentType.IfBlock -> {
                val field = (node.props.firstOrNull { it is Prop.StateRef } as? Prop.StateRef)?.field ?: ""
                sb.append(ind).append("<block wx:if=\"{{$field}}\">\n")
                node.children.forEach { emitNode(sb, it, depth + 1) }
                sb.append(ind).append("</block>\n")
            }
            ComponentType.Spacer -> {
                val cls = node.style?.className
                sb.append(ind).append("<view")
                if (cls != null) sb.append(" class=\"$cls\"")
                sb.append("/>\n")
            }
            else -> {
                sb.append(ind).append("<${node.type.wxmlTag}")
                val cls = node.style?.className
                if (cls != null) sb.append(" class=\"$cls\"")
                emitProps(sb, node)
                emitEvents(sb, node)
                val text = textContent(node)
                if (node.children.isEmpty() && text == null) {
                    sb.append("/>\n")
                } else {
                    sb.append(">")
                    if (text != null) sb.append(text)
                    if (node.children.isNotEmpty()) {
                        sb.append("\n")
                        node.children.forEach { emitNode(sb, it, depth + 1) }
                        sb.append(ind)
                    }
                    sb.append("</${node.type.wxmlTag}>\n")
                }
            }
        }
    }

    private fun textContent(node: UiNode): String? {
        if (node.type != ComponentType.Text && node.type != ComponentType.Button) return null
        val p = node.props.firstOrNull() ?: return null
        return renderProp(p)
    }

    private fun emitProps(sb: StringBuilder, node: UiNode) {
        for (p in node.props) {
            when (p) {
                is Prop.Literal -> {
                    if (p.text.startsWith("mode:")) sb.append(" mode=\"").append(p.text.removePrefix("mode:")).append("\"")
                    else if (p.text.startsWith("placeholder:")) sb.append(" placeholder=\"").append(p.text.removePrefix("placeholder:")).append("\"")
                    else if (p.text == "scroll-y") sb.append(" scroll-y")
                    else if (node.type == ComponentType.Image) sb.append(" src=\"").append(p.text).append("\"")
                }
                is Prop.Bool -> if (p.v && node.type == ComponentType.Image) sb.append(" lazy-load")
                is Prop.StateRef -> if (node.type == ComponentType.Input) sb.append(" value=\"{{${p.field}}}\"")
                    else if (node.type == ComponentType.Image) sb.append(" src=\"{{${p.field}}}\"")
                is Prop.LoopVar -> if (node.type == ComponentType.Image) sb.append(" src=\"{{${p.varName}.${p.field}}}\"")
                is Prop.Num -> {}
            }
        }
    }

    private fun emitEvents(sb: StringBuilder, node: UiNode) {
        // 循环内事件节点注入 data-index：事件回调通过 e.currentTarget.dataset.index 定位当前行
        if (node.loop != null && node.events.isNotEmpty()) sb.append(" data-index=\"{{index}}\"")
        for (e in node.events) sb.append(" ${e.eventAttr}=\"${e.handlerId}\"")
    }

    private fun renderProp(p: Prop): String = when (p) {
        is Prop.Literal -> p.text
        is Prop.Num -> p.v.toString()
        is Prop.Bool -> p.v.toString()
        is Prop.StateRef -> "{{${p.field}}}"
        is Prop.LoopVar -> "{{${p.varName}.${p.field}}}"
    }
}

object WxssGenerator {

    fun generate(tree: UiTree): String {
        val sb = StringBuilder()
        sb.append("/* auto-generated by compose-miniapp transpiler */\n")
        collect(tree.root).forEach { (cls, decls) ->
            sb.append(".$cls {\n")
            decls.forEach { (prop, value) -> sb.append("  $prop: $value;\n") }
            sb.append("}\n")
        }
        return sb.toString()
    }

    private fun collect(node: UiNode): List<Pair<String, List<Pair<String, String>>>> {
        val out = mutableListOf<Pair<String, List<Pair<String, String>>>>()
        node.style?.let { out.add(it.className to it.declarations) }
        node.children.forEach { out.addAll(collect(it)) }
        return out
    }
}
